backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

backend/base/urls.py
from django.urls import path
from . import views 

app_name = 'base'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('room/<str:channelName>', views.Room.as_view(), name='room'),
    path('getToken/', views.Token.as_view(), name='token'),
    path('createUser/', views.CreateUser.as_view(), name='postUser'),
    path('getMember/', views.GetMember.as_view(), name='get_member'),
    path('delMember/', views.DeleteUser.as_view(), name='delete_member'),
]

backend/base/models.py
from django.db import models

# Create your models here.
class RoomMember(models.Model):
    name = models.CharField(max_length=34)
    uid = models.CharField(max_length=233, unique=True)
    RoomName = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.RoomName} --> {self.name}"  
      

backend/base/views.py
from agora_token_builder import RtcTokenBuilder
from django.http import JsonResponse, Http404
from django.views.generic import TemplateView, DetailView
from django.views import View
import random as rand
import time
import json
from .models import RoomMember
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

class Index(TemplateView):
    template_name = 'base/index.html'

class Room(TemplateView):
    template_name = 'base/room.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['channelName'] = kwargs['channelName']
        return context

    # use this method to print the channelName and Username in html file
    # def render_to_response(self, context: dict[str, Any], **response_kwargs: Any):
    #     return render(self.request, self.template_name, context, **response_kwargs)
        
class Token(TemplateView):

    def get(self, request, *args, **kwargs):
        return self.get_token(request)
    
    def get_token(self, request):
        appId = "a39bdeba8e97439586641d7af2c66192"
        appCertificate = "0c6917030a85421c89d7a87a9bdb13d2"
        channelName = request.GET.get('channelName')
        uid = rand.randint(0, 231)
        role = 1
        expirationTime = 3600 * 24
        currentTime = time.time()
        privilegeExpiredTs = currentTime + expirationTime
        token = RtcTokenBuilder.buildTokenWithUid(appId, appCertificate, channelName, uid, role, privilegeExpiredTs)

        return JsonResponse({
            "token" : token,
            "uid" : uid  
            }, safe = False)

@method_decorator(csrf_exempt, name="dispatch")
class CreateUser(View):
    model = RoomMember
    
    # creating or getting the info about the user 
    def post(self, request, *args, **kwargs):
        #request.body gives you a raw HTTP request body as a bytestring. 
        # You can convert into a dictionary using json.loads()
        data = json.loads(request.body)
        print(data)
        member, created = self.model.objects.get_or_create(
            name = data['name'],
            uid = data['uid'],
            RoomName = data['roomName']
        )

        return JsonResponse({'name':data['name']}, safe=False)
    



class GetMember(DetailView):
    model = RoomMember

    def get(self, request, *args,**kwargs):
        uid = request.GET.get('uid')
        room = request.GET.get('room')
        
        print(f"{uid}, {room}")

        member = self.model.objects.get(
            uid = uid,
            RoomName = room,
        )        
        print("Joined - " , member.name)
        return JsonResponse({'name':member.name}, safe=False)
        

class ErrorPage(TemplateView):
    template_name = "base/error.html"


@method_decorator(csrf_exempt, name="dispatch")
class DeleteUser(View):
    model = RoomMember
    
    # deleting the user info
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        member = self.model.objects.get(
            name = data['name'],
            uid = data['uid'],
            RoomName = data['roomName']
        )
        member.delete()
        return JsonResponse("Member was Deleted", safe=True)

backend/base/templates/base/Error.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link type="text/css" rel="stylesheet" href="{% static 'CSS/Error.css'%}">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <link href="{% static 'images/favicon.png' %}" type="image/x-icon" rel="icon"/>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="error-template">
                        <h1>
                            Oops!</h1>
                        <h2>
                            404 Not Found</h2>
                        <div class="error-details">
                            Sorry, an error has occured, Requested page not found!
                        </div>
                        <div class="error-actions">
                            <a href="{% url 'base:index' %}" class="btn btn-outline-info btn-lg">
                            <span class="glyphicon glyphicon-home"> </span> Take Me Home </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>    
    </body>
</html>

backend/base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>SnapVideo</title>
        {% load static %}
        <link href="{% static 'CSS/styles.css' %}" type="text/css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

        <link href="{% static 'images/favicon.png' %}" type="image/x-icon" rel="icon"/>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <a class="navbar-brand brand" href="{% url 'base:index'%}">ChatRoom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% comment %} <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    </ul>
                </div> {% endcomment %}
            </div>
        </nav>
    
        {%block content%}

        {%endblock content%}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    </body>
</html>

backend/base/templates/base/index.html
{% extends "base/base.html"%}
{% load static %}
{% load bootstrap5 %}
{% block content %}

<div class="form-container ">
    <div id="logo-container" >
        <img id="logo"  src="{% static 'images/logo.png' %}">
    </div>
    <div class="card-body mb-1" id="welcome-container">
        <h3 class="welcome-message">Welcome Adventurer</h3>
        <p>Enter your Desired Room</p>
    </div>

    <form id="form">
        <div class="form-floating mb-3">
            <input type="text" name="name" class="form-control" id="name" placeholder="Username">
            <label for="floatingInput">Enter Your Name</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" name="room" class="form-control" id="channel" placeholder="Channel Name">
            <label for="floatingInput">Enter Room Name</label>
        </div>

        <input class="btn btn-dark btn-lg active" type="submit" value="Join Stream" />
    </form>
</div>
<script type="text/javascript" src="{% static 'JS/join.js' %}"></script>
{% endblock content %}

backend/base/templates/base/room.html
{% extends "base/base.html"%}
{% load static %}
{% block content %}

<main class="room-container">
    <section id="room-name-wrapper">
        <p class="room-name">Room Name - <span id="room-name"></span></p>
    </section>
    <section id="video-streams">    </section>
    <section id="controls-wrapper">
        <div class="icon-wrapper ">
            <img class="mic-button rounded controls-button" id="mic-btn" src="{% static 'images/microphone.svg' %}" alt="Microphone" \>
        </div>
        <div class="icon-wrapper ">
            <img class="video-button rounded controls-button" id="video-btn" src="{% static 'images/video.svg' %}" alt="Video/Camera" \>
        </div>
        <div class="icon-wrapper">
            <img class="leave-button rounded controls-button" id="leave-btn" src="{% static 'images/leave.svg' %}" alt="Signing Out" \>
        </div>
    </section>
</main>
<script type="text/javascript" src="{% static 'Assets/AgoraRTC_N-4.18.2.js' %}"></script>
<script type="text/javascript" src="{% static 'JS/stream.js'%}"></script>
{% endblock content %}